sudo: required
language: c
os:
  - linux
  - osx
env:
  matrix:
    - CI_TARGET=clang
    - CI_TARGET=gcc
matrix:
  include:
    - os: osx
      env: CI_TARGET=clang
      compiler: clang
    - os: osx
      env: CI_TARGET=gcc
      compiler: gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get update;
      sudo apt-get install python-dev
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi
install:
  - git clone https://github.com/libuv/libuv.git
  - cd libuv && sh autogen.sh && ./configure && make && make check && sudo make install
  - sudo pip install grequests
script:
  - ./install.sh test
