language: c
sudo: required
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get update;
      sudo apt-get install python-dev;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi
install:
  - sudo pip install requests grequests
  - if [ $TRAVIS_OS_NAME = linux ]; then
      git clone https://github.com/libuv/libuv.git && cd libuv;
      libtoolize;
      aclocal;
      aclocal -I m4;
      automake --add-missing --copy;
      autoconf;
      git clone https://chromium.googlesource.com/external/gyp.git build/gyp;
      ./configure && make && make check;
      sudo make install;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew install --HEAD libuv;
    fi
script:
  - ./install.sh test
  - sudo ./install.sh install