language: c
sudo: required
os:
  - linux
  - osx

compiler:
  - clang
  - gcc
    
branches:
  only:
    - master
    
cache:
  - pip
  
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get update;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi
    
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      git clone https://github.com/libuv/libuv.git && cd libuv;
      sh autogen.sh || sh autogen.sh;
      ./configure && make;
      sudo make install;
      sudo ldconfig;
      cd ..;

      sudo apt-get install -y libjson0 libjson0-dev sqlite3 libsqlite3-dev redis-server;
      git clone https://github.com/redis/hiredis.git;
      cd hiredis;
      make;
      sudo make install;
      cd ..;
    fi

before_script:
  - pip install --user grequests
  - export PATH=$HOME/.local/bin:$HOME/Library/Python/2.7/bin/:$PATH
  
script:
  - ./install.sh && ./install.sh test
