language: c
sudo: required
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get update;
      sudo apt-get install build-essential;
      sudo apt-get install python-dev;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      git clone https://github.com/libuv/libuv.git && cd libuv;
      sh autogen.sh || sh autogen.sh;
      ./configure && make;
      sudo make install;
      cd ..;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew install --HEAD libuv;
    fi
script:
  - ls /usr/local/include
  - ls /usr/local/lib | grep libuv
  - echo $PATH