language: c
sudo: required
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get update;
      sudo apt-get install python-dev;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi
install:
  - git clone https://github.com/libuv/libuv.git
  - cd libuv
  - wget -q https://gist.githubusercontent.com/pmq20/837c0c8e175eba9eb0e4/raw/00d01205efb54ea242e53088ee8339ec4231939f/autogen.sh -O autogen.sh
  - sh autogen.sh && ./configure && make && make check && sudo make install
  - sudo pip install requests grequests
script:
  - ./install.sh test
